# This rule is not used by the project foo-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to domain.openmcp.cloud resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: foo-operator
    app.kubernetes.io/managed-by: kustomize
  name: foo-viewer-role
rules:
- apiGroups:
  - domain.openmcp.cloud
  resources:
  - foos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - domain.openmcp.cloud
  resources:
  - foos/status
  verbs:
  - get
